# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - GamaEdtech

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      
     
      

      # Install EF Core tools
      - name: Install dotnet ef
        run: |
            dotnet tool install --global dotnet-ef --version 9.*
            dotnet tool restore

      


      # Run migrations for the DataSource project
      - name: Run EF Core Migrations
        run: |
          cd src/GamaEdtech.Back.DataSource
          dotnet ef database update   
        env:
          AZURE_SQL_CONNECTIONSTRING: ${{ secrets.AZURE_SQL_CONNECTIONSTRING }}
        # dotnet ef migrations bundle-o ${{env.DOTNET_ROOT}}/myapp/migrationsbundle

      # Build the main project
      - name: Build Gateway Project
        run: |
          cd src/GamaEdtech.Back.Gateway.Rest
          dotnet build --configuration Release

      # Publish the main project
      - name: Publish Gateway Project
        run: |
          cd src/GamaEdtech.Back.Gateway.Rest
          dotnet publish --configuration Release -o ${{env.DOTNET_ROOT}}/myapp


      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E7AD42DCE0E3458688EEC58144A99363 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4FAD1FFCF5D846C0B2F9EC41A93BEB1B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_70A0E0AF59F74CDB872D720B1C186289 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gamaapi'
          slot-name: 'Production'
          package: .
          
