name: Build, Migrate, and Deploy ASP.Net Core app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Build the main project
      - name: Build Gateway Project
        run: |
          cd src/GamaEdtech.Back.Gateway.Rest
          dotnet build --configuration Release

      # Publish the main project
      - name: Publish Gateway Project
        run: |
          cd src/GamaEdtech.Back.Gateway.Rest
          dotnet publish --configuration Release -o ${{env.DOTNET_ROOT}}/myapp

      # Install EF Core tools
      - name: Install dotnet ef
        run: dotnet tool install --global dotnet-ef --version 9.*

      # Run migrations for the DataSource project
      # - name: Run EF Core Migrations
        #run: |
         # cd src/GamaEdtech.Back.DataSource
          #dotnet ef database update 

      # Upload artifact for deployment
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E42B5113ACF94145963E674ED1373C24 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F9BE20A127EF41688B7BECB70A3D0488 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_90EA3F3D9BF045B59BB93F25E3BAD1CA }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GamaEdtechV2'
          slot-name: 'Production'
          package: .
